# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

project: 'drail-project'
program: drail/main.py
method: grid
name: Walker-wail-2traj
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  
parameters:
  action-input:
    value: false
  alg:
    value: wail
  clip-actions:
    value: true
  cuda:
    value: true
  entropy-coef:
    value: 0.001
  env-name:
    value: Walker2d-v3
  eval-interval:
    value: 20000
  eval-num-processes:
    value: 1
  log-interval:
    value: 1
  disc-lr:
    value: 0.0000005
    # values: [0.000002, 0.000001, 0.0000005]
    # value: 0.000001
  lr:
    value: 0.0001
    # values: [0.0002, 0.0001, 0.00005]
  max-grad-norm:
    value: 0.5
  normalize-env:
    value: true
  num-env-steps:
    value: 25000000
  num-epochs:
    value: 10
  num-eval:
    value: 2
  num-mini-batch:
    value: 32
  num-render:
    value: 1000
  num-steps:
    value: 128
  ppo-hidden-dim:
    value: 256
  prefix:
    value: wail
  regularize-epsilon:
    value: 0.01
  reward-type:
    value: positive
  save-interval:
    value: 100000
  seed:
    values: [1,2,3,4,5]
    # value: 2
  traj-batch-size:
    value: 128
  traj-frac:
    value: 1
  traj-load-path:
    value: ./expert_datasets/ppo_walker_2.pt
  vid-fps:
    value: 100
  wail-reward-norm:
    value: true
  wail-state-norm:
    value: true
    